num1 = int(input("Enter your first number: "))
num2 = int(input("Enter your second number: "))
print("Your result: ", num1 + num2)
print("Your result: ", num1 - num2)
print("Your result: ", num1 * num2)
print("Your result: ", num1 / num2)
print("Your result: ", num1 ** num2)
print("Your result: ", num1 // num2)
